# 服务器配置
server:
  port: "8801"
  mode: "debug"  # debug, release, test
  read_timeout: "30s"
  write_timeout: "30s"

# 数据库配置
database:
  driver: "mysql"
  dsn: ""  # 从环境变量 Mysql 读取
  max_idle_conns: 20
  max_open_conns: 100
  conn_max_lifetime: "1h"
  log_level: "info"  # silent, error, warn, info

# Redis配置
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

# JWT配置
jwt:
  signing_key: ""  # 从环境变量 JWT_SIGNING_KEY 读取
  expiry: "24h"
  refresh_expiry: "168h"  # 7天
  issuer: "nasa-go-admin"
  enable_blacklist: true

# MongoDB配置
mongodb:
  databases:
    admin_log_db:
      uri: "mongodb://localhost:27017"
      collections:
        logs: "logs"
        another_collection: "another_collection"
    app_log_db:
      uri: "mongodb://localhost:27017"
      collections:
        logs: "logs"
        another_collection: "another_collection"
    business_metrics_db:
      uri: "mongodb://localhost:27017"
      collections:
        metrics: "metrics"
    system_metrics_db:
      uri: "mongodb://localhost:27017"
      collections:
        metrics: "metrics"
    default_log_db:
      uri: "mongodb://localhost:27017"
      collections:
        logs: "logs"
    booking_log_db:
      uri: "mongodb://localhost:27017"
      collections:
        logs: "logs"
    websocket_log_db:
      uri: "mongodb://localhost:27017"
      collections:
        connection_logs: "connection_logs"
        event_logs: "event_logs"
    notification_log_db:
      uri: "mongodb://localhost:27017"
      collections:
        push_records: "push_records"
        notification_logs: "notification_logs"
        admin_user_receive_records: "admin_user_receive_records"
        admin_user_online_status: "admin_user_online_status"

# 日志配置
log:
  level: "info"          # debug, info, warn, error
  format: "json"         # json, text
  output: "stdout"       # stdout, file, both
  file_path: "logs/app.log"
  max_size: 100          # MB
  max_backups: 7
  max_age: 30            # days

# 安全配置
security:
  enable_https: false
  tls_cert_file: ""
  tls_key_file: ""
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://localhost:9848"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"
    - "http://127.0.0.1:9848"
    # 局域网段支持（开发环境）
    - "http://192.168.*:*"
    - "http://10.*:*"
    - "http://172.16.*:*"
  trusted_proxies:
    - "127.0.0.1"
  rate_limit: 1000       # 每分钟请求数
  enable_rate_limit: true